layout_spectrum: 0.4928315
color:
  saturation: 0.6200865
  brandStrength: 0.9418853
  lightness: 0.7927604
  brandColors:
    - '#333333'
    - '#F9F9F9'
    - '#A3A3A3'
  rhythmicContrast: 0.7491339
typography_spectrum: 0.4641577
name: Heewon
