color:
  saturation: 0.6200865
  brandStrength: 0.9418853
  rhythmicContrast: 0.7491339
  brandColors:
    - '#333333'
    - '#F9F9F9'
    - '#A3A3A3'
  lightness: 0.7927604
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.4928315
typography_spectrum: 0.4641577
name: Heewon
